language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
install:
  - wget https://raw.githubusercontent.com/axibase/atsd/master/.travis-functions.sh && source .travis-functions.sh
  - install_checkers_in_non_doc_project
script:
  - mvn install -Dgpg.skip
  - spellcheck
  - linkcheck
  - stylecheck
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
dist: trusty
