language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
install:
  - wget https://raw.githubusercontent.com/axibase/atsd/master/.travis-functions.sh && source .travis-functions.sh
  - install_checkers_in_non_doc_project
script:
  - mvn install -Dgpg.skip
  - spellcheck
  - linkcheck
  - stylecheck
jdk:
  - openjdk8
dist: trusty
notifications:
  webhooks: https://apps.axibase.com/api/v1/messages/wk-travis-ci/travis-ci?json.parse=payload&exclude=payload.id;payload.number;payload.config*;payload.repository*;payload.matrix*;payload.*commit*;payload.status_message;payload.result&include=payload.repository.name&command.message=payload.result_message
