site_name: Aggregation Logger Documentation
site_url: http://axibase.com/products/axibase-time-series-database/writing-data/aggregation-log-filter/
repo_url: https://github.com/axibase/aggregation-log-filter.git
repo_name: GitHub
site_description: Documentation for Aggregation Logger

docs_dir: .
include_search: true

pages:
- Aggregation Logger: index.md

nav:
<ul>
  {% for nav_item in nav %}
      {% if nav_item.children %}
          <li>{{ nav_item.title }}
              <ul>
              {% for nav_item in nav_item.children %}
                  <li class="{% if nav_item.active%}current{%endif%}">
                      <a href="{{ nav_item.url }}">{{ nav_item.title }}</a>
                  </li>
              {% endfor %}
              </ul>
          </li>
      {% else %}
          <li class="{% if nav_item.active%}current{%endif%}">
              <a href="{{ nav_item.url }}">{{ nav_item.title }}</a>
          </li>
      {% endif %}

  {% endfor %}
</ul>