site_name: Aggregation Logger Documentation
site_url: http://axibase.com/products/axibase-time-series-database/writing-data/aggregation-log-filter/
repo_url: https://github.com/axibase/aggregation-log-filter.git
repo_name: GitHub
site_description: Documentation for Aggregation Logger

docs_dir: .
include_search: true

pages:
- Aggregation Logger: README.md
