name: Build Aggregation Log Filter

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java_version: ['1.8', '11', '15']

    name: Run tests under Java ${{matrix.java_version}}
    runs-on: ubuntu-latest

    steps:
      - uses: axibase/checkout@v2
      - name: Cache local Maven repository
        uses: axibase/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK for Java ${{matrix.java_version}}
        uses: axibase/setup-java@v1
        with:
          java-version: ${{matrix.java_version}}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [ spelling_retext, spelling_yandex, links, style, anchors ]

    steps:
      - uses: axibase/checkout@v2
        with:
          fetch-depth: 0
      - name: Running ${{ matrix.linter }} linter
        uses: axibase/docs-linter@v1
        with:
          linter: ${{ matrix.linter }}
